[WIP]Support for Heading sensor
mutualmobile/ComposeSensors pull request #11
Opened 2023-03-30 05:32 UTC by Adi-MMandroid

###Tested on:
Device :-

2023-04-06 07:52 UTC, Adi-MMandroid commented
@shubhamsinghmutualmobile not able to get this sensor to work on my device, isAvailable is false, could you get someone to test this please?

2023-05-19 10:47 UTC, shubhamsinghmutualmobile commented on composesensors/src/main/java/com/mutualmobile/composesensors/HeadingSensorState.kt
> +    val isAvailable: Boolean = false
We also include the `accuracy` parameter in all our state classes in ComposeSensors. Refer to any one of them for more info.

2023-05-19 10:48 UTC, shubhamsinghmutualmobile commented on composesensors/src/main/java/com/mutualmobile/composesensors/HeadingSensorState.kt
> +class HeadingSensorState(
Also, we want this class' constructor to be internal as we want our users to make use of the composable function only.

2023-05-19 10:49 UTC, shubhamsinghmutualmobile commented
@Adi-MMandroid We can remove the `[WIP]` prefix from this PR's title 👍

2023-05-19 10:56 UTC, shubhamsinghmutualmobile requested changes
@Adi-MMandroid Let's address the comments and also make the required change to the `README.md` file and mark this sensor's state as ✅ there.

2023-05-19 13:16 UTC, shubhamsinghmutualmobile commented
Commit history will be cleaner if we squash these commits ✅

2023-05-19 13:42 UTC, closed without merging