feat: Step Detector Sensor Implementation
mutualmobile/ComposeSensors pull request #16
Opened 2023-03-30 10:55 UTC by swap-musale

2023-03-30 13:59 UTC, shubhamsinghmutualmobile commented on README.md
> +Step Detector | ✅️ | rememberStepDetectorSensorState
Please add `()` after the method name i.e. `rememberStepDetectorSensorState()`

2023-03-30 14:02 UTC, shubhamsinghmutualmobile requested changes

2023-03-30 14:58 UTC, swap-musale commented on composesensors/src/main/java/com/mutualmobile/composesensors/StepDetectorSensorState.kt
> +    val steps: Float = 0f,
Noted

2023-03-31 05:57 UTC, shubhamsinghmutualmobile approved these changes

2023-03-31 06:00 UTC, merged