[WIP]Support for Gyroscope Limited Axes sensor
mutualmobile/ComposeSensors pull request #43
Opened 2023-04-07 17:15 UTC by Chandra-Mauli-Sharma

In ref. to #40.
- The support for the Gyroscope Limited Axes sensor is added.
- WIP tag added to Readme.md for Gyroscope Limited Axes sensor until approval.

2023-04-14 13:25 UTC, shubhamsinghmutualmobile requested changes

2023-04-14 13:25 UTC, shubhamsinghmutualmobile commented on composesensors/src/main/java/com/mutualmobile/composesensors/GyroscopeLimitedAxesSensorState.kt
> +) {
Let's please name the file according to https://github.com/mutualmobile/ComposeSensors/issues/40 i.e. `LimitedAxesGyroscopeSensorState`, give it proper documentation, and use the same parameter names as the already implemented `GyroscopeSensorState` class for better API cohesion (please refer [GyroscopeSensorState.kt](https://github.com/mutualmobile/ComposeSensors/blob/main/composesensors/src/main/java/com/mutualmobile/composesensors/GyroscopeSensorState.kt)).

2023-04-20 08:13 UTC, Chandra-Mauli-Sharma commented on composesensors/src/main/java/com/mutualmobile/composesensors/GyroscopeLimitedAxesSensorState.kt
> +fun rememberGyroscopeLimitedAxesSensorState(
I have made the PR resolving the requested changes. Sorry for the delay

2023-04-20 10:50 UTC, shubhamsinghmutualmobile approved these changes

2023-04-20 10:51 UTC, shubhamsinghmutualmobile commented
Let's fix the ktlint issues and we should be good to go for this PR @Chandra-Mauli-Sharma ✅

2023-04-20 12:55 UTC, shubhamsinghmutualmobile commented
<img width="904" alt="Screenshot 2023-04-20 at 6 24 26 PM" src="https://user-images.githubusercontent.com/89389061/233372168-3af5d2d1-f9b7-4412-9a81-afd2510ba943.png">

@Chandra-Mauli-Sharma could you also please `Update branch` to the latest code from `development`?

2023-04-20 12:55 UTC, Chandra-Mauli-Sharma commented
Done

2023-04-20 12:57 UTC, shubhamsinghmutualmobile approved these changes

2023-04-20 12:58 UTC, merged